In [22]:
import pandas as pd
df = pd.read_csv('dataset/SpotifyAudioFeaturesNov2018.csv')

In [23]:
df.head()

artist_name                track_id  \
0          YG  2RM4jf1Xa9zPgMGRDiht8O   
1          YG  1tHDG53xJNGsItRA3vfVgs   
2       R3HAB  6Wosx2euFPMT14UXiWudMy   
3  Chris Cooq  3J2Jpw61sO7l6Hc7qdYV91   
4  Chris Cooq  2jbYvQCyPgX3CdmAzeVeuS   

                                       track_name  acousticness  danceability  \
0  Big Bank feat. 2 Chainz, Big Sean, Nicki Minaj      0.005820         0.743   
1                    BAND DRUM (feat. A$AP Rocky)      0.024400         0.846   
2                                   Radio Silence      0.025000         0.603   
3                                         Lactose      0.029400         0.800   
4                             Same - Original mix      0.000035         0.783   

   duration_ms  energy  instrumentalness  key  liveness  loudness  mode  \
0       238373   0.339             0.000    1    0.0812    -7.678     1   
1       214800   0.557             0.000    8    0.2860    -7.259     1   
2       138913   0.723             0.000    9    0.0824    -5.890     0   
3       125381   0.579             0.912    5    0.0994   -12.118     0   
4       124016   0.792             0.878    7    0.0332   -10.277     1   

   speechiness    tempo  time_signature  valence  popularity  
0       0.4090  203.927               4    0.118          44  
1       0.4570  159.009               4    0.371          10  
2       0.0454  114.966               4    0.382          63  
3       0.0701  123.003               4    0.641           9  
4       0.0661  120.047               4    0.928           8

In [57]:
df_features = df.drop(columns=['artist_name', 'track_id', 'track_name'])

In [59]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [60]:
X = scaler.fit_transform(df_features)

/anaconda3/envs/sandbox/lib/python3.6/site-packages/sklearn/preprocessing/data.py:625: DataConversionWarning:

Data with input dtype int64, float64 were all converted to float64 by StandardScaler.

/anaconda3/envs/sandbox/lib/python3.6/site-packages/sklearn/base.py:462: DataConversionWarning:

Data with input dtype int64, float64 were all converted to float64 by StandardScaler.



In [53]:
from sklearn.neighbors import KDTree

In [93]:
%%time
tree = KDTree(X)
dist, ind = tree.query(X, k=11)

CPU times: user 6min 50s, sys: 2.49 s, total: 6min 52s
Wall time: 6min 59s


# New query

In [189]:
import numpy as np
song = X[0].reshape(1,-1)
song

array([[-0.96090184,  0.84544747,  0.20774432, -0.90048509, -0.63325362,
        -1.17647113, -0.67505048,  0.3485406 ,  0.80373949,  2.38617385,
         2.79665214,  0.23005083, -1.2343496 ,  1.10222341]])

In [197]:
dist, ind = tree.query(song, k=11)

In [198]:
neighbors = ind[0]

In [199]:
df.iloc[neighbors]

artist_name                track_id  \
0                    YG  2RM4jf1Xa9zPgMGRDiht8O   
95873       Iggy Azalea  3EOuVx8f5Bb9AIt3PrRHKO   
22119       Kuzu Mellow  61KEpN0YvwDrwaqqT65ecD   
38864         Joey Trap  0X8XHADrYzkNGK7AlEZNBN   
8443             Outlaw  0UGcmjbvLBf7JR4PHntTpd   
101583    Blac Youngsta  7Jbt6KWzS8cpP1xnW0tQ96   
29862             Gjiko  1qEu5WXxkmh4nwldLYJgYC   
113771           Ca$his  0MiAP4EQGIuikH23RTyP53   
107896  Shoreline Mafia  75OGmcs4DTNJqWHCKTGegx   
113505       Smokepurpp  3cYNoOv4SEWPIZmh34JrUv   
106525         Lil Durk  3XcnvbkurHelpe04EETr9k   

                                               track_name  acousticness  \
0          Big Bank feat. 2 Chainz, Big Sean, Nicki Minaj       0.00582   
95873                                     Tokyo Snow Trip       0.00787   
22119                                                 4 U       0.02020   
38864                       Seal (feat. Almighty Suspect)       0.01080   
8443    Shot Caller from a Holler (feat. Redneck Soulj...       0.02100   
101583                                          Beginners       0.00272   
29862                 Shtrejt (feat. Lumi B & Ledri Vula)       0.00585   
113771                                               What       0.00497   
107896                                         Dope House       0.10300   
113505                             Pray (feat. A$AP Ferg)       0.00738   
106525                                           Way More       0.10500   

        danceability  duration_ms  energy  instrumentalness  key  liveness  \
0              0.743       238373   0.339          0.000000    1    0.0812   
95873          0.744       130547   0.447          0.000026    1    0.1690   
22119          0.718       192181   0.404          0.000014    1    0.1970   
38864          0.683       156446   0.540          0.000000    0    0.0958   
8443           0.723       221178   0.593          0.000182    2    0.1810   
101583         0.762       121680   0.392          0.000000    1    0.1100   
29862          0.836       251625   0.479          0.000003    1    0.1150   
113771         0.753       152704   0.502          0.000000    1    0.0903   
107896         0.784       172384   0.356          0.000007    1    0.2230   
113505         0.752       156000   0.491          0.000000    1    0.1110   
106525         0.718       272721   0.455          0.000000    1    0.1210   

        loudness  mode  speechiness    tempo  time_signature  valence  \
0         -7.678     1        0.409  203.927               4   0.1180   
95873    -10.486     1        0.401  196.585               4   0.2440   
22119     -7.926     1        0.413  179.998               4   0.3220   
38864     -5.381     1        0.534  200.332               4   0.1910   
8443      -7.003     1        0.333  179.932               4   0.0836   
101583    -8.873     1        0.502  176.839               4   0.3190   
29862    -10.218     1        0.397  160.065               4   0.2070   
113771    -8.804     1        0.313  169.834               4   0.2190   
107896    -8.717     1        0.438  161.460               4   0.1650   
113505    -7.501     1        0.375  159.966               4   0.1320   
106525    -7.109     1        0.316  161.027               4   0.1990   

        popularity  
0               44  
95873           52  
22119           40  
38864           39  
8443            38  
101583          42  
29862           41  
113771          49  
107896          51  
113505          56  
106525          55

In [200]:
song2 = np.array([[-0.98,  0.1,  0.5, -0.3, -0.63325362,
        -1.17647113, -0.2,  0.3485406 ,  0.4,  1,
         2.79665214,  0.5, -1.2343496 ,  1.2]])
song2

array([[-0.98      ,  0.1       ,  0.5       , -0.3       , -0.63325362,
        -1.17647113, -0.2       ,  0.3485406 ,  0.4       ,  1.        ,
         2.79665214,  0.5       , -1.2343496 ,  1.2       ]])

In [206]:
%time
dist, ind = tree.query(X[0].reshape(1,-1), k=11)

CPU times: user 11 µs, sys: 3 µs, total: 14 µs
Wall time: 26 µs


In [217]:
dist

array([[0.        , 1.37347419, 1.41376023, 1.59029844, 1.60519909,
        1.72476191, 1.73459969, 1.73533608, 1.83830707, 1.86294253,
        1.87079087]])

In [218]:
ind

array([[     0,  95873,  22119,  38864,   8443, 101583,  29862, 113771,
        107896, 113505, 106525]])

In [207]:
df.iloc[ind[0]]

artist_name                track_id  \
0                    YG  2RM4jf1Xa9zPgMGRDiht8O   
95873       Iggy Azalea  3EOuVx8f5Bb9AIt3PrRHKO   
22119       Kuzu Mellow  61KEpN0YvwDrwaqqT65ecD   
38864         Joey Trap  0X8XHADrYzkNGK7AlEZNBN   
8443             Outlaw  0UGcmjbvLBf7JR4PHntTpd   
101583    Blac Youngsta  7Jbt6KWzS8cpP1xnW0tQ96   
29862             Gjiko  1qEu5WXxkmh4nwldLYJgYC   
113771           Ca$his  0MiAP4EQGIuikH23RTyP53   
107896  Shoreline Mafia  75OGmcs4DTNJqWHCKTGegx   
113505       Smokepurpp  3cYNoOv4SEWPIZmh34JrUv   
106525         Lil Durk  3XcnvbkurHelpe04EETr9k   

                                               track_name  acousticness  \
0          Big Bank feat. 2 Chainz, Big Sean, Nicki Minaj       0.00582   
95873                                     Tokyo Snow Trip       0.00787   
22119                                                 4 U       0.02020   
38864                       Seal (feat. Almighty Suspect)       0.01080   
8443    Shot Caller from a Holler (feat. Redneck Soulj...       0.02100   
101583                                          Beginners       0.00272   
29862                 Shtrejt (feat. Lumi B & Ledri Vula)       0.00585   
113771                                               What       0.00497   
107896                                         Dope House       0.10300   
113505                             Pray (feat. A$AP Ferg)       0.00738   
106525                                           Way More       0.10500   

        danceability  duration_ms  energy  instrumentalness  key  liveness  \
0              0.743       238373   0.339          0.000000    1    0.0812   
95873          0.744       130547   0.447          0.000026    1    0.1690   
22119          0.718       192181   0.404          0.000014    1    0.1970   
38864          0.683       156446   0.540          0.000000    0    0.0958   
8443           0.723       221178   0.593          0.000182    2    0.1810   
101583         0.762       121680   0.392          0.000000    1    0.1100   
29862          0.836       251625   0.479          0.000003    1    0.1150   
113771         0.753       152704   0.502          0.000000    1    0.0903   
107896         0.784       172384   0.356          0.000007    1    0.2230   
113505         0.752       156000   0.491          0.000000    1    0.1110   
106525         0.718       272721   0.455          0.000000    1    0.1210   

        loudness  mode  speechiness    tempo  time_signature  valence  \
0         -7.678     1        0.409  203.927               4   0.1180   
95873    -10.486     1        0.401  196.585               4   0.2440   
22119     -7.926     1        0.413  179.998               4   0.3220   
38864     -5.381     1        0.534  200.332               4   0.1910   
8443      -7.003     1        0.333  179.932               4   0.0836   
101583    -8.873     1        0.502  176.839               4   0.3190   
29862    -10.218     1        0.397  160.065               4   0.2070   
113771    -8.804     1        0.313  169.834               4   0.2190   
107896    -8.717     1        0.438  161.460               4   0.1650   
113505    -7.501     1        0.375  159.966               4   0.1320   
106525    -7.109     1        0.316  161.027               4   0.1990   

        popularity  
0               44  
95873           52  
22119           40  
38864           39  
8443            38  
101583          42  
29862           41  
113771          49  
107896          51  
113505          56  
106525          55

# Other code

In [159]:
similars = []
for row in ind:
    indexes = [x for x in row]
    ids = [df.loc[x].track_id for x in indexes]
    similars.append(ids)

In [163]:
cols = ['id', 'sim1', 'sim2', 'sim3', 'sim4', 'sim5', 'sim6', 'sim7', 'sim8', 'sim9', 'sim10']
df2 = pd.DataFrame(similars, columns=cols)

In [209]:
df3 = df2.drop_duplicates(subset=['id'], keep='first')

In [213]:
df3.to_csv('similars.csv')

In [214]:
tree

In [215]:
import pickle

In [216]:
# Dump the trained decision tree classifier with Pickle
decision_tree_pkl_filename = 'trained_tree.pkl'
# Open the file to save as pkl file
decision_tree_model_pkl = open(decision_tree_pkl_filename, 'wb')
pickle.dump(tree, decision_tree_model_pkl)
# Close the pickle instances
decision_tree_model_pkl.close()